#!/bin/sh

. /usr/lib/seedex/common.sh

case "$DEVICENAME" in
"$SEEDEX_PROXY_IFACE_PREFIX"[0-9]*) ;;
*) exit 0 ;;
esac

case "$ACTION" in
add) /etc/init.d/seedex-proxy attach "$DEVICENAME" ;;
remove) /etc/init.d/seedex-proxy detach "$DEVICENAME" ;;
esac
