#!/bin/sh

set -e

[ -z "${IPKG_INSTROOT:-}" ] || exit 0

rm -f /tmp/luci-indexcache /tmp/luci-indexcache.* 2>/dev/null || true
rm -rf /tmp/luci-modulecache 2>/dev/null || true
/etc/init.d/rpcd reload 2>/dev/null || true

exit 0
